'use strict';

// The published CSV URL is intentionally read-only. Never place passwords,
// service-account JSON, private API keys, or write credentials in this file.
const SHEET_CSV_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSwC4M_tZxvU3iFkjJQhNFixELWUCEjAdwR4EnAdvdDd6x_7hIhbbz5EO6-2EmNGkt3CW4rxWHViM9g/pub?gid=0&single=true&output=csv';
const FALLBACK_LOGO = 'assets/ezra-logo.jpg';
const demo = [
 {title:'TNPSC Group II & IIA',department:'Tamil Nadu Public Service Commission',category:'TNPSC',description:'Recruitment opportunity for eligible degree holders.',postName:'Group II / IIA Posts',vacancies:'Various',qualification:'Any Degree',ageLimit:'As per notification',salary:'As per post',fee:'As per notification',selection:'Written Exam / Interview as applicable',location:'Tamil Nadu',startDate:'-',lastDate:'30 Sep 2026',howToApply:'Read the notification carefully and apply through the official portal.',applyLink:'#',notificationLink:'#',officialWebsite:'#',departmentLogo:'',status:'New',featured:'Yes',sponsored:'No',id:'demo-1'},
 {title:'Junior Assistant Recruitment',department:'State Government Department',category:'State',description:'Latest state government recruitment opportunity.',postName:'Junior Assistant',vacancies:'250+',qualification:'12th / Degree',ageLimit:'As per notification',salary:'As per rules',fee:'As per notification',selection:'Written Exam',location:'Tamil Nadu',startDate:'-',lastDate:'05 Oct 2026',howToApply:'Complete the online application with correct details.',applyLink:'#',notificationLink:'#',officialWebsite:'#',departmentLogo:'',status:'New',featured:'Yes',sponsored:'Yes',id:'demo-2'},
 {title:'Railway Apprentice',department:'Indian Railways',category:'Railway',description:'Apprentice vacancies in Indian Railways.',postName:'Apprentice',vacancies:'500+',qualification:'10th + ITI',ageLimit:'As per notification',salary:'Stipend as per rules',fee:'As per notification',selection:'Merit Based',location:'Various',startDate:'-',lastDate:'12 Oct 2026',howToApply:'Apply online through the official railway recruitment portal.',applyLink:'#',notificationLink:'#',officialWebsite:'#',departmentLogo:'',status:'Open',featured:'Yes',sponsored:'No',id:'demo-3'},
 {title:'Bank Clerk Recruitment',department:'Banking Sector',category:'Banking',description:'Banking recruitment for eligible graduates.',postName:'Clerk',vacancies:'1000+',qualification:'Any Degree',ageLimit:'As per notification',salary:'As per bank rules',fee:'As per notification',selection:'Online Exam',location:'Various',startDate:'-',lastDate:'18 Oct 2026',howToApply:'Apply online after checking eligibility and notification.',applyLink:'#',notificationLink:'#',officialWebsite:'#',departmentLogo:'',status:'Open',featured:'No',sponsored:'No',id:'demo-4'}
];
let jobs=[...demo], cat='All';
const $=s=>document.querySelector(s);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const yes=x=>String(x??'').trim().toLowerCase()==='yes';
function safeUrl(value,{allowHash=false}={}){const raw=String(value??'').trim();if(!raw)return '';if(allowHash&&raw==='#')return '#';try{const u=new URL(raw,location.href);if(u.protocol==='https:'||u.protocol==='http:')return u.href;if(u.origin===location.origin&&u.protocol==='')return u.href;}catch{}return '';}
function safeImage(value){const u=safeUrl(value);return u||FALLBACK_LOGO;}
function norm(r,i){return {id:String(r['Job ID']||r.ID||'row-'+(i+1)).trim(),title:String(r['Job Title']||r.Title||'').trim(),department:String(r.Department||'').trim(),category:String(r.Category||'Other').trim(),description:String(r['Short Description']||r.Description||'').trim(),fullDetails:String(r['Full Details']||'').trim(),postName:String(r['Post Name']||'').trim(),vacancies:String(r.Vacancies||'-').trim(),qualification:String(r.Qualification||'-').trim(),ageLimit:String(r['Age Limit']||'-').trim(),salary:String(r.Salary||'-').trim(),fee:String(r['Application Fee']||r.Fee||'-').trim(),selection:String(r['Selection Process']||r.Selection||'-').trim(),location:String(r['Job Location']||r.Location||'-').trim(),startDate:String(r['Start Date']||'-').trim(),lastDate:String(r['Last Date']||'-').trim(),howToApply:String(r['How to Apply']||'-').trim(),applyLink:String(r['Apply Link']||'#').trim(),notificationLink:String(r['Notification Link']||'#').trim(),officialWebsite:String(r['Official Website']||'#').trim(),departmentLogo:String(r['Department Logo']||r.Logo||'').trim(),status:String(r.Status||'Open').trim(),featured:String(r.Featured||'No').trim(),sponsored:String(r.Sponsored||'No').trim()};}
function parseCSV(text){const rows=[];let row=[],val='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){val+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(val.trim());val='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(val.trim());if(row.some(Boolean))rows.push(row);row=[];val='';}else val+=c;}if(val!==''||row.length){row.push(val.trim());if(row.some(Boolean))rows.push(row);}if(rows.length<2)return [];const h=rows[0].map(x=>x.trim());return rows.slice(1).map((r,i)=>{const o={};h.forEach((k,n)=>o[k]=r[n]??'');return norm(o,i);}).filter(j=>j.title);}
function detailUrl(j){return 'job.html?job='+encodeURIComponent(j.id);}
function logoFor(j){return safeImage(j.departmentLogo);}
function card(j){return `<article class="job-card"><div class="card-top"><span class="category-tag">${esc(j.category)}</span>${yes(j.sponsored)?'<span class="sponsor-tag">SPONSORED</span>':`<span class="status-tag">${esc(j.status)}</span>`}</div><div class="job-head"><img class="dept-logo" src="${esc(logoFor(j))}" alt="Department logo" loading="lazy" onerror="this.onerror=null;this.src='${FALLBACK_LOGO}'"><div><h3><a href="${detailUrl(j)}">${esc(j.title)}</a></h3><p>${esc(j.department||'Department not specified')}</p></div></div><div class="job-meta"><span><b>QUALIFICATION</b>${esc(j.qualification)}</span><span><b>VACANCIES</b>${esc(j.vacancies)}</span><span><b>LAST DATE</b>${esc(j.lastDate)}</span><span><b>LOCATION</b>${esc(j.location)}</span></div><a class="card-action" href="${detailUrl(j)}">View job details <span>→</span></a></article>`;}
function render(){const q=$('#search')?.value.toLowerCase().trim()||'';const f=jobs.filter(j=>(cat==='All'||j.category.toLowerCase()===cat.toLowerCase())&&Object.values(j).join(' ').toLowerCase().includes(q));if($('#jobsGrid'))$('#jobsGrid').innerHTML=f.map(card).join('');if($('#featuredGrid')){const top=f.filter(j=>yes(j.featured));$('#featuredGrid').innerHTML=(top.length?top:f.slice(0,3)).map(card).join('');}if($('#empty'))$('#empty').classList.toggle('hidden',f.length!==0);if($('#count'))$('#count').textContent=String(jobs.length);}
async function load(){try{const r=await fetch(SHEET_CSV_URL,{method:'GET',cache:'no-store'});if(!r.ok)throw new Error('sheet fetch failed');const d=parseCSV(await r.text());if(d.length)jobs=d;if($('#updated'))$('#updated').textContent='Live from Google Sheets • '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}catch{if($('#updated'))$('#updated').textContent='Showing fallback listings';}render();}
function setupUI(){document.querySelectorAll('.pill').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');cat=b.dataset.cat||'All';render();}));const search=$('#search');search?.addEventListener('input',render);$('#searchBtn')?.addEventListener('click',()=>{document.querySelector('#jobs')?.scrollIntoView({behavior:'smooth'});render();});const theme=$('#theme');theme?.addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('ezra-theme',document.body.classList.contains('dark')?'dark':'light');});if(localStorage.getItem('ezra-theme')==='dark')document.body.classList.add('dark');const menu=$('#menu'),nav=$('#mainNav');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('show');menu.setAttribute('aria-expanded',String(open));});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('show');menu?.setAttribute('aria-expanded','false');}));}
function info(label,value){return `<div class="info-item"><span>${esc(label)}</span><strong>${esc(value||'-')}</strong></div>`;}
function externalLink(label,value,primary=false){const u=safeUrl(value,{allowHash:true});return u&&u!=='#'?`<a class="detail-link ${primary?'primary':''}" href="${esc(u)}" target="_blank" rel="noopener noreferrer">${label} <span>↗</span></a>`:'';}
async function loadJobDetails(){const box=$('#detail');if(!box)return;let id=new URLSearchParams(location.search).get('job')||'';try{const r=await fetch(SHEET_CSV_URL,{cache:'no-store'});if(!r.ok)throw new Error();const d=parseCSV(await r.text());if(d.length)jobs=d;}catch{}const j=jobs.find(x=>x.id===id)||jobs.find(x=>x.title===id);if(!j){box.innerHTML='<div class="not-found"><div class="not-found-icon">?</div><h1>Job not found</h1><p>This job may have been removed or the link may be invalid.</p><a class="card-action" href="index.html#jobs">Back to Job Alerts</a></div>';return;}document.title=j.title+' | EZRA Job Alerts';const details=j.fullDetails?`<section class="detail-section"><div class="section-label">FULL DESCRIPTION</div><h2>About this opportunity</h2><div class="rich-text">${esc(j.fullDetails).replace(/\n/g,'<br>')}</div></section>`:'';const apply=externalLink('Apply Online',j.applyLink,true);const notice=externalLink('Download Notification',j.notificationLink);const official=externalLink('Official Website',j.officialWebsite);box.innerHTML=`<article class="detail-shell"><aside class="detail-side"><div class="logo-frame"><img src="${esc(logoFor(j))}" alt="${esc(j.department||'Department')} logo" onerror="this.onerror=null;this.src='${FALLBACK_LOGO}'"></div><span class="category-tag">${esc(j.category)}</span><span class="side-status">${esc(j.status)}</span><h1>${esc(j.title)}</h1><p>${esc(j.department||'Department not specified')}</p><div class="side-mini"><span>LAST DATE</span><strong>${esc(j.lastDate)}</strong></div></aside><div class="detail-main"><div class="detail-intro"><span class="section-label">JOB DETAILS</span>${j.description?`<p>${esc(j.description)}</p>`:''}</div><section class="detail-section"><div class="section-label">AT A GLANCE</div><h2>Job overview</h2><div class="info-grid">${info('Post Name',j.postName)}${info('Vacancy',j.vacancies)}${info('Qualification',j.qualification)}${info('Age Limit',j.ageLimit)}${info('Salary',j.salary)}${info('Application Fee',j.fee)}${info('Selection Process',j.selection)}${info('Job Location',j.location)}</div></section>${details}<section class="detail-section"><div class="section-label">TIMELINE</div><h2>Important dates</h2><div class="timeline"><div><span>START DATE</span><strong>${esc(j.startDate)}</strong></div><div><span>LAST DATE</span><strong>${esc(j.lastDate)}</strong></div></div></section><section class="detail-section"><div class="section-label">APPLICATION</div><h2>How to apply</h2><div class="rich-text">${esc(j.howToApply||'-').replace(/\n/g,'<br>')}</div></section><section class="links-section"><div class="section-label">OFFICIAL LINKS</div><div class="link-grid">${apply}${notice}${official}</div></section></div></article>`;}
setupUI();if($('#jobsGrid'))load();if($('#detail'))loadJobDetails();
