// ================= EZRA JOB ALERTS =================
// Google Sheet CSV URL
const SHEET_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSwC4M_tZxvU3iFkjJQhNFixELWUCEjAdwR4EnAdvdDd6x_7hIhbbz5EO6-2EmNGkt3CW4rxWHViM9g/pub?gid=0&single=true&output=csv";

const demo=[
{title:"TNPSC Group II & IIA",department:"Tamil Nadu Public Service Commission",category:"TNPSC",description:"Recruitment opportunity for eligible degree holders.",postName:"Group II / IIA Posts",vacancies:"Various",qualification:"Any Degree",ageLimit:"As per notification",salary:"As per post",fee:"As per notification",selection:"Written Exam / Interview as applicable",location:"Tamil Nadu",startDate:"-",lastDate:"30 Sep 2026",howToApply:"Read the notification carefully and apply through the official portal.",applyLink:"#",notificationLink:"#",officialWebsite:"#",departmentLogo:"",status:"New",featured:"Yes",sponsored:"No",id:"demo-1"},
{title:"Junior Assistant Recruitment",department:"State Government Department",category:"State",description:"Latest state government recruitment opportunity.",postName:"Junior Assistant",vacancies:"250+",qualification:"12th / Degree",ageLimit:"As per notification",salary:"As per rules",fee:"As per notification",selection:"Written Exam",location:"Tamil Nadu",startDate:"-",lastDate:"05 Oct 2026",howToApply:"Complete the online application with correct details.",applyLink:"#",notificationLink:"#",officialWebsite:"#",departmentLogo:"",status:"New",featured:"Yes",sponsored:"Yes",id:"demo-2"},
{title:"Railway Apprentice",department:"Indian Railways",category:"Railway",description:"Apprentice vacancies in Indian Railways.",postName:"Apprentice",vacancies:"500+",qualification:"10th + ITI",ageLimit:"As per notification",salary:"Stipend as per rules",fee:"As per notification",selection:"Merit Based",location:"Various",startDate:"-",lastDate:"12 Oct 2026",howToApply:"Apply online through the official railway recruitment portal.",applyLink:"#",notificationLink:"#",officialWebsite:"#",departmentLogo:"",status:"Open",featured:"Yes",sponsored:"No",id:"demo-3"},
{title:"Bank Clerk Recruitment",department:"Banking Sector",category:"Banking",description:"Banking recruitment for eligible graduates.",postName:"Clerk",vacancies:"1000+",qualification:"Any Degree",ageLimit:"As per notification",salary:"As per bank rules",fee:"As per notification",selection:"Online Exam",location:"Various",startDate:"-",lastDate:"18 Oct 2026",howToApply:"Apply online after checking eligibility and notification.",applyLink:"#",notificationLink:"#",officialWebsite:"#",departmentLogo:"",status:"Open",featured:"No",sponsored:"No",id:"demo-4"}
];

let jobs=[...demo],cat="All";
const $=s=>document.querySelector(s);
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const yes=x=>String(x??"").trim().toLowerCase()==="yes";
function norm(r,i){return{ id:r["Job ID"]||r.ID||("row-"+(i+1)), title:r["Job Title"]||r.Title||"", department:r.Department||"", category:r.Category||"Other", description:r["Short Description"]||r.Description||"", fullDetails:r["Full Details"]||"", postName:r["Post Name"]||"", vacancies:r.Vacancies||"-", qualification:r.Qualification||"-", ageLimit:r["Age Limit"]||"-", salary:r.Salary||"-", fee:r["Application Fee"]||r.Fee||"-", selection:r["Selection Process"]||r.Selection||"-", location:r["Job Location"]||r.Location||"-", startDate:r["Start Date"]||"-", lastDate:r["Last Date"]||"-", howToApply:r["How to Apply"]||"-", applyLink:r["Apply Link"]||"#", notificationLink:r["Notification Link"]||"#", officialWebsite:r["Official Website"]||"#", departmentLogo:r["Department Logo"]||r["Logo"]||"", status:r.Status||"Open", featured:r.Featured||"No", sponsored:r.Sponsored||"No"};}
function parseCSV(text){let rows=[],row=[],val="",q=false;for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){val+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(val.trim());val="";}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(val.trim());if(row.some(x=>x!==""))rows.push(row);row=[];val="";}else val+=c;}if(val!==""||row.length){row.push(val.trim());if(row.some(x=>x!==""))rows.push(row);}if(rows.length<2)return[];let h=rows[0];return rows.slice(1).map((r,i)=>{let o={};h.forEach((k,n)=>o[k]=r[n]??"");return norm(o,i);}).filter(j=>j.title);}
function detailUrl(j){return "job.html?job="+encodeURIComponent(j.id);}
function logoFor(j){return j.departmentLogo||((j.officialWebsite&&j.officialWebsite!=="#")?"https://www.google.com/s2/favicons?domain="+encodeURIComponent(j.officialWebsite)+"&sz=128":"assets/ezra-logo.jpg")}
function card(j){return `<article class="card"><div class="badges"><span class="badge">${esc(j.category)}</span>${yes(j.sponsored)?'<span class="badge sponsor">SPONSORED</span>':'<span class="badge">'+esc(j.status)+'</span>'}</div><div class="job-brand"><img class="dept-logo" src="${esc(logoFor(j))}" alt="Department logo" onerror="this.onerror=null;this.src='assets/ezra-logo.jpg'"><div class="dept-wrap"><h3><a href="${detailUrl(j)}">${esc(j.title)}</a></h3><div class="dept">${esc(j.department)}</div></div></div><div class="meta"><div><b>QUALIFICATION</b>${esc(j.qualification)}</div><div><b>VACANCIES</b>${esc(j.vacancies)}</div><div><b>LAST DATE</b>${esc(j.lastDate)}</div><div><b>TYPE</b>${esc(j.category)}</div></div><a class="apply" href="${detailUrl(j)}">View Full Details →</a></article>`}
function render(){let q=$("#search")?.value.toLowerCase().trim()||"";let f=jobs.filter(j=>(cat==="All"||j.category.toLowerCase()===cat.toLowerCase())&&Object.values(j).join(" ").toLowerCase().includes(q));if($("#jobsGrid"))$("#jobsGrid").innerHTML=f.map(card).join("");if($("#featuredGrid")){let top=f.filter(j=>yes(j.featured));$("#featuredGrid").innerHTML=(top.length?top:f.slice(0,3)).map(card).join("");}if($("#empty"))$("#empty").classList.toggle("hidden",!!f.length);if($("#count"))$("#count").textContent=jobs.length+"+";}
async function load(){if(!SHEET_CSV_URL){render();return}try{let r=await fetch(SHEET_CSV_URL);if(!r.ok)throw Error();let d=parseCSV(await r.text());if(d.length)jobs=d;if($("#updated"))$("#updated").textContent="Live from Google Sheets • "+new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});render();}catch(e){if($("#updated"))$("#updated").textContent="Sheet unavailable • demo data";render();}}
function setupUI(){document.querySelectorAll(".pill").forEach(b=>b.onclick=()=>{document.querySelectorAll(".pill").forEach(x=>x.classList.remove("active"));b.classList.add("active");cat=b.dataset.cat;render();});if($("#search"))$("#search").oninput=render;if($("#theme"))$("#theme").onclick=()=>document.body.classList.toggle("dark");if($("#menu"))$("#menu").onclick=()=>document.querySelector("nav")?.classList.toggle("show");}
async function loadJobDetails(){setupUI();let box=$("#detail");if(!box)return;let id=new URLSearchParams(location.search).get("job");try{let r=await fetch(SHEET_CSV_URL);if(!r.ok)throw Error();let d=parseCSV(await r.text());if(d.length)jobs=d;}catch(e){}let j=jobs.find(x=>x.id===id)||jobs.find(x=>x.title===id);if(!j){box.innerHTML='<div class="not-found"><h1>Job not found</h1><p>This job may have been removed or the link is invalid.</p><a class="apply" href="index.html#jobs">Back to Job Alerts</a></div>';return;}document.title=j.title+" | EZRA Job Alerts";let links=`<div class="important-links"><h2>Important Links</h2><div class="link-grid">${j.applyLink&&j.applyLink!=="#"?`<a class="big-link primary" href="${esc(j.applyLink)}" target="_blank" rel="noopener">Apply Online ↗</a>`:""}${j.notificationLink&&j.notificationLink!=="#"?`<a class="big-link" href="${esc(j.notificationLink)}" target="_blank" rel="noopener">Download Notification ↗</a>`:""}${j.officialWebsite&&j.officialWebsite!=="#"?`<a class="big-link" href="${esc(j.officialWebsite)}" target="_blank" rel="noopener">Official Website ↗</a>`:""}</div></div>`;box.innerHTML=`<article class="detail-card"><div class="detail-hero"><div class="detail-brand"><img class="detail-logo" src="${esc(logoFor(j))}" alt="${esc(j.department)} logo" onerror="this.onerror=null;this.src='assets/ezra-logo.jpg'"><div class="detail-title"><div class="detail-top"><div><div class="badges"><span class="badge">${esc(j.category)}</span>${yes(j.sponsored)?'<span class="badge sponsor">SPONSORED</span>':''}</div><h1>${esc(j.title)}</h1><p>${esc(j.department)}</p></div><span class="status-pill">${esc(j.status)}</span></div></div></div></div>${j.description?`<div class="intro">${esc(j.description)}</div>`:""}<div class="detail-body">${j.fullDetails?`<section class="detail-section"><h2>Job Details</h2><div class="long-text">${esc(j.fullDetails).replace(/\n/g,"<br>")}</div></section>`:""}<section class="detail-section"><h2>Job Overview</h2><div class="info-table">${info("Post Name",j.postName)}${info("Vacancy",j.vacancies)}${info("Qualification",j.qualification)}${info("Age Limit",j.ageLimit)}${info("Salary",j.salary)}${info("Application Fee",j.fee)}${info("Selection Process",j.selection)}${info("Job Location",j.location)}</div></section><section class="detail-section"><h2>Important Dates</h2><div class="info-table">${info("Application Start Date",j.startDate)}${info("Last Date",j.lastDate)}</div></section>${j.howToApply?`<section class="detail-section"><h2>How to Apply</h2><div class="long-text">${esc(j.howToApply).replace(/\n/g,"<br>")}</div></section>`:""}${links}</div></article>`;}
function info(k,v){return `<div><span>${esc(k)}</span><strong>${esc(v||"-")}</strong></div>`;}
setupUI();if($("#jobsGrid"))load();
